export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";
export const SAVE_RECORD_SUCCESS = "SAVE_RECORD_SUCCESS";
export const TOGGLE_RECORD_SUCCESS = "TOGGLE_RECORD_SUCCESS";
export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";