export default {
  "title": " Lista de Tarefas Minimalista",
  "editTodo": "Editar Tarefa",
  "createTodo": "Criar Nova Tarefa",
  "back": "Anterior",
  "notFound": "Não Encontrado",
  "filter": "Filtrar",
  "all": "All",
  "notDone": "Incompleto",
  "done": "Completo",
  "sort": "Classificar",
  "newestFirst": "Novo para Antigo",
  "oldestFirst": "Antigo para Novo",
  "save": "Save",
  "delete": "Excluir",
  "textRequired": "O texto é obrigatório",
  "noTodos": "Sem tarefas. Clique no botão abaixo para adicionar.",
  "allDone": "Parabéns. Todas as tarefas concluídas!",
  "todoRemaining": "{0} de {1} {2}",
  "todo": "tarefa restante",
  "todos": "tarefas restantes",
};