export default {
  "title": "React App",
  "editRecord": "Edit",
  "createRecord": "Create New",
  "back": "Back",
  "notFound": "Not Found",
  "filter": "Filter",
  "all": "All",
  "sort": "Sort",
  "newestFirst": "Date New to Old",
  "oldestFirst": "Date Old to New",
  "save": "Save",
  "delete": "Delete",
  "textRequired": "Text is required",
  "noRecords": "No records. Click the button below to add.",
  "recordCount": "{0} {1} total",
  "record": "record",
  "records": "records",
};