export default {
  "title": " Minimalist Todo List",
  
  "textRequired": "Text is required",
  "noTodos": "You have no todos. Click the button below to add.",
  "allDone": "Congrats. You completed all your todos!",
  "todoRemaining": "{0} of {1} {2} remaining",
  "todo": "todo",

  "appTitle": "Records App",
  "notFound": "Page not found",
  "back": "Back",
  "home": "Home",
  "about": "About",
  "recordsTitle": "Records",
  "records": "records",
  "createRecord": "Create New Record",
  "editRecord": "Edit Record",
  "loadingRecordsFailed": "Loading records failed. {0}",
  "recordDeleted": "Record deleted",
  "deleteFailed": "Delete failed. {0}",
  "toggleFailed": "Toggle failed. {0}",
  "filterFailed": "Filter failed. {0}",
  "sortFailed": "Sort failed. {0}",
  "recordSaved": "Record saved",
  "saving": "Saving...",
  "save": "Save",
  "delete": "Delete",
  "filter": "Filter",
  "all": "All",
  "notDone": "Not Done",
  "done": "Done",
  "sort": "Sort",
  "newestFirst": "Date New to Old",
  "oldestFirst": "Date Old to New",
  "aboutText": "This app uses React, Redux, React Router, and many other helpful libraries.",
  "homeText": "React, Redux and React Router for ultra-responsive web apps.",
  "learnMore": "Learn more",
  "errorText": "Text is required.",
};