export default {
  "title": " Liste de Tâches Minimaliste",
  "editTodo": "Modifier la Tâche",
  "createTodo": "Créer Une Tâche",
  "back": "Retour",
  "notFound": "Introuvable",
  "filter": "Filtre",
  "all": "Toute",
  "notDone": "Pas terminé",
  "done": "Terminé",
  "sort": "Trier",
  "newestFirst": "Date Nouveau à Ancien",
  "oldestFirst": "Date Ancienne à Nouvelle",
  "save": "Enregistrement",
  "delete": "Supprimer",
  "textRequired": "Texte requis",
  "noTodos": "Aucune tâche. Cliquez sur le bouton ci-dessous pour ajouter.",
  "allDone": "Toutes nos félicitations. Vous avez terminé toutes vos tâches!",
  "todoRemaining": "{0} sur {1} {2} restant.",
  "todo": "tâche",
  "todos": "les tâches",
};