export default {
  // Generic
  "back": "Retour",
  "notFound": "Introuvable",
  "filter": "Filtre",
  "all": "Toute",
  "notDone": "Pas terminé",
  "done": "Terminé",
  "sort": "Trier",
  "newestFirst": "Date Nouveau à Ancien",
  "oldestFirst": "Date Ancienne à Nouvelle",
  "save": "Enregistrement",
  "delete": "Supprimer",
  "home": "Accueil",
  "about": "À propos",
  "saving": "Enregistrement...",
  "recordSaved": "Enregistré",

  // Custom
  "appTitle": "Application des enregistrements",
  "recordsTitle": "Records",
  "records": "enregistrements",
  "createRecord": "Créer un nouvel enregistrement",
  "editRecord": "Modifier l'enregistrement",
  "loadingRecordsFailed": "Le chargement des enregistrements a échoué. {0}",
  "recordDeleted": "Enregistrement supprimé",
  "deleteFailed": "La suppression a échoué. {0}",
  "toggleFailed": "Le basculement a échoué. {0}",
  "filterFailed": "Le filtre a échoué. {0}",
  "sortFailed": "Le tri a échoué. {0}",
  "aboutText": "Cette application utilise React, Redux, React Router et de nombreuses autres bibliothèques utiles.",
  "homeText": "React, Redux et React Router pour des applications Web ultra-réactives.",
  "learnMore": "Apprendre encore plus",
  "textError": "Le texte est requis.",
};