export default {
  // Generic
  "back": "Назад",
  "notFound": "Не найдено",
  "filter": "Фильтр",
  "all": "все",
  "notDone": "неполный",
  "done": "полный",
  "sort": "сортировка",
  "newestFirst": "Новое в старое",
  "oldestFirst": "Старый в новый",
  "save": "Сохранить",
  "delete": "удаление",
  "home": "Главная",
  "about": "О программе",
  "saving": "Сохранение...",
  "recordSaved": "Сохранено",
  "recordDeleted": "удалено",

  // Custom
  "appTitle": "Приложение записей",
  "recordsTitle": "записей",
  "records": "записей",
  "createRecord": "Создать новую запись",
  "editRecord": "Редактировать запись",
  "loadingRecordsFailed": "Загрузка записей не удалась. {0}",
  "deleteFailed": "Удалить не удалось. {0}",
  "toggleFailed": "Переключить не удалось. {0}",
  "filterFailed": "Фильтр не выполнен. {0}",
  "sortFailed": "Сортировка не удалась. {0}",
  "aboutText": "Это приложение использует React, Redux, React Router и многие другие полезные библиотеки.",
  "homeText": "React, Redux и React Router для сверхчувствительных веб-приложений.",
  "learnMore": "Выучить больше",
  "textError": "Текст обязателен.",
};