export default {
  "title": " 极简任务列表",
  "editTodo": "编辑任务",
  "createTodo": "创建新任务",
  "back": "返回",
  "notFound": "未找到",
  "filter": "筛选",
  "all": "所有",
  "notDone": "不完整",
  "done": "完成",
  "sort": "排序",
  "newestFirst": "新到旧",
  "oldestFirst": "旧到新",
  "save": "保存",
  "delete": "删除​​",
  "textRequired": "文字为必填项",
  "noTodos": "没有任务。点击下面的按钮添加。",
  "allDone": "恭喜你。所有任务已完成。",
  "todoRemaining": "剩余{1}个{2}中的{0}个",
  "todo": "任务",
  "todos": "任务",
};