export default {
  // Generic
  "back": "Anterior",
  "notFound": "Não Encontrado",
  "filter": "Filtrar",
  "all": "All",
  "notDone": "Incompleto",
  "done": "Completo",
  "sort": "Classificar",
  "newestFirst": "Novo para Antigo",
  "oldestFirst": "Antigo para Novo",
  "save": "Save",
  "delete": "Excluir",
  "home": "Início",
  "about": "Sobre",
  "saving": "Salvando...",
  "recordSaved": "Salvo",
  "recordDeleted": "Excluída",

  // Custom
  "appTitle": "Aplicação de registros",
  "recordsTitle": "Registros",
  "records": "registros",
  "createRecord": "Criar novo registro",
  "editRecord": "Editar registro",
  "loadingRecordsFailed": "O carregamento dos registros falhou. {0}",
  "deleteFailed": "Falha na exclusão. {0}",
  "toggleFailed": "A alternância falhou. {0}",
  "filterFailed": "O filtro falhou. {0}",
  "sortFailed": "Falha na classificação. {0}",
  "aboutText": "Este aplicativo usa React, Redux, React Router e muitas outras bibliotecas úteis.",
  "homeText": "React, Redux e React Router para aplicativos da web ultra-responsivos.",
  "learnMore": "Saber mais",
  "textError": "O texto é obrigatório.",
};