export default {
  // Generic
  "back": "Back",
  "notFound": "Page not found",
  "filter": "Filter",
  "all": "All",
  "notDone": "Not Done",
  "done": "Done",
  "sort": "Sort",
  "newestFirst": "Date New to Old",
  "oldestFirst": "Date Old to New",
  "save": "Save",
  "delete": "Delete",
  "home": "Home",
  "about": "About",
  "saving": "Saving...",
  "recordSaved": "Record saved",
  "recordDeleted": "Record deleted",

  // Custom
  "appTitle": "Records App",
  "recordsTitle": "Records",
  "records": "records",
  "createRecord": "Create New Record",
  "editRecord": "Edit Record",
  "loadingRecordsFailed": "Loading records failed. {0}",
  "deleteFailed": "Delete failed. {0}",
  "toggleFailed": "Toggle failed. {0}",
  "filterFailed": "Filter failed. {0}",
  "sortFailed": "Sort failed. {0}",
  "aboutText": "This app uses React, Redux, React Router, and many other helpful libraries.",
  "homeText": "React, Redux and React Router for ultra-responsive web apps.",
  "learnMore": "Learn more",
  "textError": "Text is required.",
};