export default {
  "title": " Lista de Tareas Minimalistas",
  "editTodo": "Editar Tarea",
  "createTodo": "Crear Nueva Tarea",
  "back": "Devolver",
  "notFound": "No encontrado",
  "filter": "Filtrar",
  "all": "Todo",
  "notDone": "Incompleto",
  "done": "Completar",
  "sort": "Ordenar",
  "newestFirst": "Nuevo a viejo",
  "oldestFirst": "Old to New",
  "save": "Guardar",
  "delete": "Eliminar",
  "textRequired": "Se requiere texto",
  "noTodos": "No hay tareas. Haga clic en el botón de abajo para agregar.",
  "allDone": "Congratulations. All tasks completed.",
  "todoRemaining": "Queda {0} de {1} {2}",
  "todo": "tareas",
  "todos": "tareas",
};