export default {
  // Generic
  "back": "返回",
  "notFound": "未找到",
  "filter": "筛选",
  "all": "所有",
  "notDone": "不完整",
  "done": "完成",
  "sort": "排序",
  "newestFirst": "新到旧",
  "oldestFirst": "旧到新",
  "save": "保存",
  "delete": "删除​​",
  "home": "主页",
  "about": "关于",
  "saving": "正在保存...",
  "recordSaved": "已保存",
  "recordDeleted": "已删除",

  // Custom
  "appTitle": "记录应用",
  "recordsTitle": "记录",
  "records": "记录",
  "createRecord": "建立新纪录",
  "editRecord": "编辑记录",
  "loadingRecordsFailed": "加载记录失败。 {0}",
  "deleteFailed": "删除失败。 {0}",
  "toggleFailed": "切换失败。 {0}",
  "filterFailed": "筛选失败。 {0}",
  "sortFailed": "排序失败。 {0}",
  "aboutText": "这个应用程序使用React，Redux，React Router和许多其他有用的库。",
  "homeText": "用于超响应Web应用程序的React，Redux和React Router。",
  "learnMore": "学到更多",
  "textError": "必须输入文字。",
};