export default {
  // Generic
  "back": "Devolver",
  "notFound": "No encontrado",
  "filter": "Filtrar",
  "all": "Todo",
  "notDone": "Incompleto",
  "done": "Completar",
  "sort": "Ordenar",
  "newestFirst": "Nuevo a viejo",
  "oldestFirst": "Old to New",
  "save": "Guardar",
  "delete": "Eliminar",
  "home": "Inicio",
  "about": "Información",
  "saving": "Guardar en curso...",
  "recordSaved": "Guardado",
  "recordDeleted": "Eliminado",

  // Custom
  "appTitle": "Aplicación de registros",
  "recordsTitle": "Registros",
  "records": "Registros",
  "createRecord": "Crear nuevo registro",
  "editRecord": "Editar registro",
  "loadingRecordsFailed": "Cargando registros fallidos. {0}",
  "deleteFailed": "Eliminar falló. {0}",
  "toggleFailed": "Toggle falló. {0}",
  "filterFailed": "El filtro falló. {0}",
  "sortFailed": "La ordenación falló. {0}",
  "aboutText": "Esta aplicación utiliza React, Redux, React Router y muchas otras bibliotecas útiles.",
  "homeText": "React, Redux y React Router para aplicaciones web ultra sensibles.",
  "learnMore": "Aprende más",
  "textError": "Se requiere texto.",
};